module.exports = {
  projects: [
    '<rootDir>/apps/github-searcher',
    '<rootDir>/libs/github-searcher/shell',
    '<rootDir>/libs/github-searcher/user-search/shell',
    '<rootDir>/libs/github-searcher/user-search/feature-search-bar',
    '<rootDir>/libs/github-searcher/user-search/feature-user-search',
    '<rootDir>/libs/github-searcher/user-search/ui-search-bar',
    '<rootDir>/libs/github-searcher/user-search/data-access',
    '<rootDir>/libs/github-searcher/user-search/feature-search-filters',
    '<rootDir>/libs/github-searcher/user-search/ui-search-filters',
    '<rootDir>/libs/github-searcher/core/ui-layout',
    '<rootDir>/libs/github-searcher/user-search/ui-search-results',
    '<rootDir>/libs/github-searcher/user-search/feature-search-results',
    '<rootDir>/libs/github-searcher/user-search/feature-user-list',
    '<rootDir>/libs/github-searcher/user-search/ui-user-list',
    '<rootDir>/libs/github-searcher/user-search/feature-search-pagination',
    '<rootDir>/libs/github-searcher/shared/environments',
    '<rootDir>/libs/github-searcher/core/data-access',
    '<rootDir>/libs/shared/utils-router',
    '<rootDir>/libs/github-searcher/user-search/domain',
    '<rootDir>/libs/shared/utils-types',
    '<rootDir>/libs/github-searcher/user-search/shared/utils-test',
  ],
};
